### ISSUE TITLE
12.21.2023 - Suggested Topic - potential UASF on CTV and vault?

### ISSUE THREAD

**Issue by reya01** [reardencode/seattle_bitdevs#2]
Are we close to a potential UASF on CTV and vault? Not time sensitive, can wait until future meetings as needed. 

Mentioned on most recent Bitcoin.Review #57
https://bitcoin.review/podcast/episode-57/

I believe this is the github they reference in that podcast:
https://github.com/jamesob/simple-ctv-vault

**Comment by brandonblack** [comment]
Let's do it!
