### ISSUE TITLE
Multisig related

### ISSUE THREAD

**Issue by reya01** [reardencode/seattle_bitdevs#3]
Missed from last time:
Stateless 3/5 collaborative multisig with TWO institutions.

Maybe adjacent additional topics:
unchained raising personal vault to $250 fee, preciously free
Liana and new mini script wallet potential

**Comment by reardencode** [comment]
I think these topics might be best covered in the first 45 minutes today. I'll put them in the doc for that.

**Comment by reardencode** [comment]
Will be checked in soon, thanks!
